//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project01_GaraLongSpeed.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDB
    {
        public string maHDB { get; set; }
        public string maKH { get; set; }
        public string maNV { get; set; }
        public string maSP { get; set; }
        public int soLuong { get; set; }
        public double giaBan { get; set; }
        public double thanhTien { get; set; }
        public System.DateTime thoiGianB { get; set; }
    
        public virtual KH KH { get; set; }
        public virtual NV NV { get; set; }
        public virtual SP SP { get; set; }
    }
}
