//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project01_GaraLongSpeed.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDN
    {
        public string maHDN { get; set; }
        public string maNCC { get; set; }
        public string maNV { get; set; }
        public string maSP { get; set; }
        public int soLuong { get; set; }
        public double giaNhap { get; set; }
        public Nullable<double> thanhTien { get; set; }
        public Nullable<System.DateTime> thoiGianN { get; set; }
    
        public virtual NCC NCC { get; set; }
        public virtual NV NV { get; set; }
        public virtual SP SP { get; set; }
    }
}
