//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project01_GaraLongSpeed.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LongSpeedGaraMotorCycleEntities : DbContext
    {
        public LongSpeedGaraMotorCycleEntities()
            : base("name=LongSpeedGaraMotorCycleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<HDB> HDBs { get; set; }
        public virtual DbSet<HDN> HDNs { get; set; }
        public virtual DbSet<KH> KHs { get; set; }
        public virtual DbSet<loaiSP> loaiSPs { get; set; }
        public virtual DbSet<NCC> NCCs { get; set; }
        public virtual DbSet<NV> NVs { get; set; }
        public virtual DbSet<SP> SPs { get; set; }
    }
}
