//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project01_GaraLongSpeed.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SP()
        {
            this.HDBs = new HashSet<HDB>();
            this.HDNs = new HashSet<HDN>();
        }
    
        public string maSP { get; set; }
        public string tenSP { get; set; }
        public int soLuong { get; set; }
        public double giaNhap { get; set; }
        public double giaBan { get; set; }
        public string maLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDB> HDBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDN> HDNs { get; set; }
        public virtual loaiSP loaiSP { get; set; }
    }
}
